### ISSUE TITLE
Issue diplaying Realease Year

### ISSUE THREAD

**Issue by HassanNdam** [andrewbaisden/anime-dashboard-app#2]
Hi Andrew, I followed your tutorial, it's excellent and very detailed. It really helped me to understand how to set up a RESTFULL API and above all to structure my project in the form of layers (back, API, DB & front).

I was having a lot of trouble with this but now it's much clearer in my head. I followed the tutorial from A to Z in 3 days and it was OK. 

I just find that it's really designed for intermediate devs, a beginner will have difficulty understanding certain concepts and moving from one file to another. 

I have two questions: 

1) Why did you create two new tables api_anime & api_animedetails please? Why didn't you just use the anime & anime_details tables? What is the consistency between these two and in which part of Django can I see this please? 

2) I've encountered the problem with the "Release Year" display, can you please look at my code and tell me how to fix it? 

It's all here: https://github.com/HassanNdam/Application-manga.git

Thanks a lot, 

Sincerely

**Comment by andrewbaisden** [comment]
@HassanNdam thanks for the constructive feedback!

1) Great question so it was the Django script which automatically generated these tables and gave them that naming convention. You can find it in the article in this section **After defining the models, run the following commands to create the necessary database tables:.** I guess it could be possible to use the existing tables if you play around with the code somewhere.

2) What is the problem with the release year display? I tried the code on your repo and it worked. The release year filter will only filter by dates if they are present in the Anime Data List. I did not code any error handling for it so if you try to filter by a date that does not exist then it just won't show anything.

**Comment by HassanNdam** [comment]
Hello thanks for your response. 

I will try and get back to you, 

With thanks.
